# Requires setting the secrets with the following names be set to their values.
# (in the GitHub secrets page user interface)
# 1. ITCHIO_API_KEY
# 2. STEAM_USERNAME
# 3. STEAM_PASSWORD
# 4. STEAM_SHARED_SECRET
# Requires the following environment variables be set as well.
# ~v~~~~~~~~~~~~~~v~~~~~~~~~~~~~

name: Build
env:
  itchio_project: aehmttw/Tanks
  itchio_channel: Universal_JAR
  steam_app: 1660910
on:
  workflow_dispatch:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: JDK17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build
        run: ./build.sh
      - name: Version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: Tanks.jar
  itch:
    name: Itch
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Upload
        uses: robpc/itchio-upload-action@v1
        with:
          path: Tanks.jar
          project: ${{ env.itchio_project }}
          channel: ${{ env.itchio_channel }}
          version: ${{ env.version }}
          api-key: ${{ secrets.ITCHIO_API_KEY }}
  steam:
    name: Steam
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: TOTP
        uses: CyberAndrii/steam-totp@v1
        id: steam-totp
        with:
          shared_secret: ${{ secrets.STEAM_SHARED_SECRET }}
      - name: Upload
        uses: game-ci/steam-deploy@v2
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          totp: ${{ steps.steam-totp.outputs.code }}
          appId: ${{ env.steam_app }}
          buildDescription: ${{ env.version }}
          rootPath: Tanks.jar
          depot1Path: StandaloneWindows64
          depot2Path: StandaloneLinux64
          releaseBranch: release
